### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by AtomicNess123** [sinic/ednc#3]
Are there any screenshots to be able to see how notifications look? Thank you.

**Comment by sinic** [comment]
I wanted to wait with screenshots until the first stable release, but it is probably a good idea to give users at least some idea of what to expect. Not that there's all that much to see yet.

**Comment by AtomicNess123** [comment]
I may have misunderstood, but the kind of notifications that this package triggers, are not visual?

**Comment by sinic** [comment]
Desktop notifications may contain both text and images, but EDNC is not the part of the system that *creates* those notifications (if that's what you mean): client applications like Firefox, Signal, or even Emacs itself create notifications, and whether they include an image is up to them.

EDNC is the part of the system that receives (and reacts to) all those notifications. By default it also tries to display both text and icons/images in the log buffer, but users are free to customize that to their liking (e.g., to display notifications in the mode line).

Does this answer your question? [This comment](https://github.com/melpa/melpa/pull/7182#issuecomment-716549550) about the difference between EDNC and other notification packages might be helpful as well.

**Comment by AtomicNess123** [comment]
Thanks, I'll find my way 👍
