### ISSUE TITLE
ednc--get-hint errors out on valid association list

### ISSUE THREAD

**Issue by arunisaac** [sinic/ednc#4]
`ednc--get-hint` errors out on the following call. This looks like a bug. The first argument is a valid association list.

``` elisp
(ednc--get-hint '(("urgency" 1)) "urgency")
```

Thanks for writing ednc! I use it with exwm and love it!

**Comment by sinic** [comment]
> Thanks for writing ednc! I use it with exwm and love it!

Thank you, glad to hear!

> The first argument is a valid association list.

I'm not so sure about that. The [notification specification](https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html#hints) contains the following sentence:
> When adding a dictionary of hints, this type must be used, rather than putting the actual hint value in as the dictionary value.

So, the way I understand it (which is also the way the `notifications` library of Emacs interprets it when sending notifications), the code should look like this:
```elisp
(ednc--get-hint '(("urgency" (1))) "urgency")
```

Did you encounter this issue with a specific application? If programs exist in the wild that violate the spec in this way, I might add a workaround.

**Comment by arunisaac** [comment]
>> When adding a dictionary of hints, this type must be used, rather
>> than putting the actual hint value in as the dictionary value.

Makes sense, I didn't know this.

> Did you encounter this issue with a specific application? If programs
> exist in the wild that violate the spec in this way, I might add a
> workaround.

Indeed, I encountered this with
https://github.com/openstenoproject/plover . But, I don't recommend
supporting non-standard programs that violate the spec. Better to fix
the non-standard programs! :-)

Does ednc support D-Bus introspection? Quoting
https://pythonhosted.org/txdbus/dbus_overview.html,

> To support a dynamic execution environment and ease of integration,
> D-Bus includes a standard introspection mechanism for the run-time
> querying of object interfaces. The D-Bus bindings for many dynamic
> languages make use of this feature to prevent the user from needing to
> explicitly specify the remote interfaces being used.

The plover code at
https://github.com/openstenoproject/plover/blob/3e7ba1afce0baf8992d43bc411100ca18e8d0d03/plover/oslayer/log_dbus.py#L42-L45
does not specify any types. I think it tries to introspect to find the
types, and maybe because ednc does not implement introspection, it sends
out wrongly typed messages. Does that make sense?

**Comment by sinic** [comment]
>I think it tries to introspect to find the types, and maybe because ednc does not implement introspection, it sends out wrongly typed messages. Does that make sense?

Yes, you're absolutely right! I didn't realize that some programs rely on introspection even in cases like this, where the specification fully describes the expected types of everything.

I just added support for introspection, and now notifications created in the same way as by Plover work fine. If you could just confirm that your problem with Plover is gone, I can close this issue. Thanks again.

**Comment by arunisaac** [comment]
Thank you very much for the quick response!

Plover works correctly with DBus introspection now. Thank you!
