### ISSUE TITLE
Interference by `openwith.el`

### ISSUE THREAD

**Issue by sinic** [sinic/ednc#9]
This is a problem mentioned in [a YouTube video (at 21:25)](https://www.youtube.com/watch?v=StbSdYcLucE&t=1285s) by @NapoleonWils0n, first brought to my attention in issue #5. My understanding is that the third party package [`openwith.el`](https://www.metalevel.at/misc/openwith.el), in its default configuration, uses external programs to open matching files for *every* call to `insert-file-contents`, even if internal to another package (like EDNC).

Explicitly inhibiting `openwith-file-handler` is a bad idea, because who knows how many other packages do something similar?

Fortunately (for EDNC), other packages have the same problem. In particular Gnus, for which `openwith.el`'s documentation suggest modifying `mm-inhibit-file-name-handlers`. It would be best if EDNC would honor the same variable, since there's nothing mail-specific about it.

**Comment by sinic** [comment]
@NapoleonWils0n, if you could confirm that my commit fixes your problem with `openwith.el`, I could close this issue. You just need to execute the following first (if you haven't already done so for Gnus):
```elisp
(add-to-list 'mm-inhibit-file-name-handlers 'openwith-file-handler)
```

**Comment by NapoleonWils0n** [comment]
Hi Mate

i tried adding 

`
(require 'mm-util)
(add-to-list 'mm-inhibit-file-name-handlers 'openwith-file-handler)
`

but it didnt stop openwith with opening the images


this is my openwith config,
its the image section that causes the issue by open all images in every mode with an external application

`
;; openwith
(require 'openwith)

(setq openwith-associations
      (list
       (list (openwith-make-extension-regexp
              '("mpg" "mpeg" "mp3" "mp4" "m4v"
                "avi" "wmv" "wav" "mov" "flv"
                "ogm" "ogg" "mkv" "webm"))
             "mpv"
             '(file))
       (list (openwith-make-extension-regexp
              '("xbm" "pbm" "pgm" "ppm" "pnm"
                "png" "gif" "bmp" "tif" "jpeg" "jpg" "webp"))
             "nsxiv -a"
             '(file))
       (list (openwith-make-extension-regexp
              '("pdf"))
             "zathura"
             '(file))))

(openwith-mode 1)

`

at the bottom of the openwith page on the emacs wiki 
there is this section

OpenWith for interactive functions only

I found that openwith is also opening files when a file was opened non-interactively from package “dashboard”. I had to change the defun for openwith-file-handler to check (called-interactively-p):

`
(defun openwith-file-handler (operation &rest args)
  "Open file with external program, if an association is configured."
  (when (and openwith-mode (not (buffer-modified-p)) (zerop (buffer-size))
             (called-interactively-p)) [...]

`

ill see if i can get that working

[openwith emacs wiki](https://www.emacswiki.org/emacs/OpenWith)

[openwith.el](https://github.com/thisirs/openwith/blob/master/openwith.el)

update:

i tried the fix on the openwith emacs page and that didnt work either
only fix that seems to work is to comment out the image section of the openwith code block

if you  have openwith installed and configured to open images 
every time you receive a notification with ednc which had an image it will be opened with an external app

**Comment by sinic** [comment]
Just to be sure: you're running an EDNC that has my commit from today?

> OpenWith for interactive functions only

That's another possible solution for your problem, but I'm trying make it so that users don't have to go to these lengths.

**Comment by NapoleonWils0n** [comment]
Hi Mate, i re ordered my config and got it working with your latest commit
not sure what was wrong first time i tried

i double checked and images open with the correct application from within dired 
but dont open with an external application when using ednc 
either in the ednc log or using pop-to-buffer, the images are opened in emacs

i needed both these commands

`
(require 'mm-util)
(add-to-list 'mm-inhibit-file-name-handlers 'openwith-file-handler)
`

so your latest commit has fixed the issue with openwith

openwith config

`
;; openwith
(require 'mm-util)
(add-to-list 'mm-inhibit-file-name-handlers 'openwith-file-handler)

(require 'openwith)
(setq openwith-associations
      (list
       (list (openwith-make-extension-regexp
              '("mpg" "mpeg" "mp3" "mp4" "m4v"
                "avi" "wmv" "wav" "mov" "flv"
                "ogm" "ogg" "mkv" "webm"))
             "mpv"
             '(file))
       (list (openwith-make-extension-regexp
              '("xbm" "pbm" "pgm" "ppm" "pnm"
                "png" "gif" "bmp" "tif" "jpeg" "jpg" "webp"))
             "nsxiv -a"
             '(file))
       (list (openwith-make-extension-regexp
              '("pdf"))
             "zathura"
             '(file))))

(openwith-mode 1)
`

**Comment by sinic** [comment]
Great, thanks for the confirmation!
